#!/bin/bash

script_path=$(readlink -f $0)
base_dir=$(dirname $script_path)
build_dir=$base_dir/build
stamps_dir=$build_dir/stamps
out_dir=$base_dir/out
repo_dir=$out_dir/repo
rootfs_dir=$out_dir/rootfs
conf_dir=$base_dir/conf

die() {
    echo "$1"
    exit 1
}

build() {
    mkdir -p $stamps_dir

    for path in $@
    do
        local name=$(basename $path)
        local stamp_path=$stamps_dir/$name.stamp

        if [ ! -f $stamp_path ]; then
            pushd $path

            set -e
            makechrootpkg -r $build_dir -- -i
            set +e

            popd

            touch $stamp_path
        fi
    done
}

make_chroot() {
    mkdir -p $build_dir

    if [ ! -d $build_dir/root ]; then
        mkarchroot $build_dir/root base-devel
    fi
}

make_repo() {
    local packages=$(find aur custom -name '*.pkg.tar.xz')

    rm -rf $repo_dir
    mkdir -p $repo_dir

    cp $packages $repo_dir

    repo-add $repo_dir/sugaros.db.tar.gz $repo_dir/*.pkg.tar.xz
}

compose() {
    local pacman_conf_path=$build_dir/pacman.conf
    sed -e "s:@REPO_DIR@:$repo_dir:" $conf_dir/pacman.conf > $pacman_conf_path

    mkdir -p $rootfs_dir
    pacstrap -c -d -C $pacman_conf_path $rootfs_dir $PACKAGES

    local img_path=$out_dir/os.img
    local mnt_dir=/mnt

    qemu-img create $img_path 5G
    mkfs.ext4 -F $img_path
    mount -o loop $img_path $mnt_dir
    cp -r $rootfs_dir/* $mnt_dir
    umount $mnt_dir
}

(( EUID != 0 )) && die 'This script must be run as root.'

. $conf_dir/os.conf

make_chroot

build aur/icon-slicer \
      custom/python2-gwebsockets-git \
      custom/sugar-artwork-git \
      custom/sugar-datastore-git \
      custom/sugar-toolkit-gtk3-git \
      custom/sugar-git \
      custom/sugar-runner-git

make_repo

compose
