#!/bin/bash

set -e

script_path=$(readlink -f $0)
base_dir=$(dirname $script_path)
build_dir=$base_dir/build
stamps_dir=$build_dir/stamps
out_dir=$base_dir/out
repo_dir=$out_dir/repo
conf_dir=$base_dir/conf

die() {
    echo "$1"
    exit 1
}

build() {
    mkdir -p $stamps_dir

    for path in $@
    do
        local name=$(basename $path)
        local stamp_path=$stamps_dir/$name.stamp

        if [ ! -f $stamp_path ]; then
            pushd $path
            makechrootpkg -r $build_dir -- -i
            popd

            touch $stamp_path
        fi
    done
}

make_chroot() {
    mkdir -p $build_dir

    if [ ! -d $build_dir/root ]; then
        mkarchroot $build_dir/root base-devel
    fi
}

make_repo() {
    local packages=$(find aur custom -name '*.pkg.tar.xz')

    rm -rf $repo_dir
    mkdir -p $repo_dir

    cp $packages $repo_dir

    repo-add $repo_dir/sugaros.db.tar.gz $repo_dir/*.pkg.tar.xz
}

compose() {
    local pacman_conf_path=$build_dir/pacman.conf
    sed -e "s:@REPO_DIR@:$repo_dir:" $conf_dir/pacman.conf > $pacman_conf_path

    local img_path=$out_dir/os.img
    local mnt_dir=/mnt/sugaros
    local user_name=sugaros

    rm -f $img_path
    qemu-img create $img_path 5G
    mkfs.ext4 -F $img_path

    mkdir -p $mnt_dir
    mount -o loop $img_path $mnt_dir

    pacstrap -c -C $pacman_conf_path $mnt_dir $PACKAGES
    arch-chroot $mnt_dir useradd $user_name -m

    local tty_service_dir=$mnt_dir/etc/systemd/system/getty@tty1.service.d

    mkdir $tty_service_dir
    cat > $tty_service_dir/autologin.conf <<EOF
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin $user_name --noclear %I 38400 linux
EOF

    echo "[[ -z \$DISPLAY && \$XDG_VTNR -eq 1 ]] && exec startx" \
        > $mnt_dir/home/$user_name/.bash_profile

    echo "exec sugar" > $mnt_dir/home/$user_name/.xinitrc

    extlinux --install $mnt_dir/boot

    cat > $mnt_dir/boot/extlinux.conf << EOF
DEFAULT sugaros
LABEL   sugaros
SAY     Sugar OS
LINUX   /boot/vmlinuz-linux
APPEND  root=/dev/sda ro
INITRD  /boot/initramfs-linux-fallback.img
EOF

    echo "/dev/sda / ext4 defaults 0 1" >> $mnt_dir/etc/fstab

    umount $mnt_dir
}

(( EUID != 0 )) && die 'This script must be run as root.'

# FIXME makechrootpkg doesn't work otherwise
unset SUDO_USER

. $conf_dir/os.conf

make_chroot

build aur/icon-slicer \
      custom/python2-gwebsockets-git \
      custom/sugar-artwork-git \
      custom/sugar-datastore-git \
      custom/sugar-toolkit-gtk3-git \
      custom/sugar-git \
      custom/sugar-runner-git \
      custom/sugar-browse-git

make_repo

compose
